config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
    get :about_us, to: 'pages#about_us'
  resources :blog_articles
  resources :podcasts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_article.rb
class BlogArticle < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 300 }
  validates :link, presence: true
  validates :date, presence: true

  has_many_attached :photos
  has_rich_text :rich_content

  acts_as_taggable_on :tags

  scope :order_by_date, -> { order(date: :desc) }

  TAGS = ["bien-être", "santé", "performance", "entreprises", "conseils"]
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :podcast

  validates :first_name, presence: true
  validates :last_name, presence: true
  #validates :bio, presence: true

  has_one_attached :photo
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  has_many :guests

  validates :title, presence: true
  validates :description, presence: true
  #validates :link, presence: true
  validates :date, presence: true

  has_rich_text :rich_content
  has_many_attached :photos

  acts_as_taggable_on :tags

  scope :order_by_date, -> { order(date: :desc) }
end

app/models/podcast_invitation.rb
class PodcastInvitation < ApplicationRecord
  belongs_to :podcast
  belongs_to :guest

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blog_articles

  has_one_attached :avatar

  # validates :first_name, :last_name, :avatar, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/blog_articles_controller.rb
class BlogArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = BlogArticle.all.order('date DESC')
    authorize @articles
  end

  def show
    @user = current_user
  end

  def new
    @user = current_user
    @article = BlogArticle.new
    authorize @article
  end

  def create
    @article = BlogArticle.new(article_params)
    authorize @article
    @article.user = current_user
    @article.date = Time.now
    tag_list_raw = params[:blog_article][:tags].drop(1)
    @article.tag_list = tag_list_raw
    # @article.tag_list.add(:tags)
    if @article.save
        redirect_to blog_article_path(@article), notice: 'Article was successfully created.'
    else
        render 'new'
    end
  end

  def edit
    authorize @article
  end

  def update
    @article.update(article_params)
    authorize @article
    redirect_to blog_article_path(@article)
  end

  def destroy
    authorize @article
    @article.destroy
    redirect_to blog_articles_path
  end

  private

  def article_params
    params.require(:blog_article).permit(:title, :description, :rich_content, :tag_list, photos: [])
  end

  def find_article
    @article = BlogArticle.find(params[:id])
    authorize @article
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about_us ]

  def home
  end

  def about_us
  end

end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  #before_action :find_article, only: [:index]
  def index
    @podcasts = Podcast.all.order('date DESC')

    #guest = @podcast.guest
    authorize @podcasts
  end

  def show
    @user = current_user
  end

  def new
    @user = current_user
    @podcast = Podcast.new
    authorize @podcast
  end

  def create
    @podcast = Podcast.new(podcast_params)
    authorize @podcast
    @podcast.date = Time.now
    # tag_list_raw = params[:blog_article][:tags].drop(1)
    # @podcast.tag_list = tag_list_raw
    # @article.tag_list.add(:tags)
    if @podcast.save
        redirect_to podcasts_path, notice: 'Podcast episode was successfully created.'
    else
        render 'new'
    end
  end

  # def edit
  #   authorize @article
  # end

  # def update
  #   @article.update(article_params)
  #   authorize @article
  #   redirect_to blog_article_path(@article)
  # end

  # def destroy
  #   authorize @article
  #   @article.destroy
  #   redirect_to blog_articles_path
  # end

  private

  def podcast_params
    params.require(:podcast).permit(:title, :description, :small_description, :link, :date, :podcast_number, photos: [])
  end

  def find_podcast
    @podcast = Podcast.find(params[:id])
    authorize @podcast
  end

  def guest
    @guest = Guest.find(params[:id])
    authorize @podcast
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_articles/_form.html.erb
  <%= simple_form_for(@article) do |f| %>
    <%#= f.input :title %>
    <%#= f.input :description %>
    <%#= f.input :content %>
    <%#= f.button :submit %>
    <div class="form-inputs">
      <%= f.input :title %>
    </div>
    <%= f.input :tags, as: :check_boxes,
                           collection: BlogArticle::TAGS,
                           checked: @article.tag_list.add%>
    <div class="form-inputs">
      <%= f.input :description %>
    </div>

    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <!-- insert these three line of code below -->
    <div class="form-inputs">
      <%= f.rich_text_area :rich_content %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class:'button' %>
    </div>
  <% end %>

app/views/blog_articles/edit.html.erb
<div class="content-container">
  <h1>Re-bonjour</h1>
  <h4>Modifier l'article</h4>

  <%= render "form", article: @article %>

</div>

app/views/blog_articles/index.erb
<%= image_tag('https://images.unsplash.com/photo-1470468969717-61d5d54fd036?ixid=MXwxMjA3fDB8MHxzZWFyY2h8ODF8fHNwb3J0cyUyMGdpcmx8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', class: "background-home-image") %>

<div class="content-container">
 <div class="banner-small banner-container">
    <h1>L'After Work</h1>
    <h4 class="mb-4">Découvrez tous nos articles </h4>
  </div>
  <h2 class="ml-3 my-5">Filtrer par thématiques</h2>

  <% @articles.each do |article| %>
    <div class="blog-card-container">
      <% if article.photos.first %>
        <%= cl_image_tag article.photos.first.key, width: 300, crop: :fill, class:"blog-card-img" %>
      <% end %>
      <div class="blog-card-text-content">
        <div class="blog-card-content">
          <div class="card-title-content">
            <h2><%= link_to article.title, blog_article_path(article) %></h2>
            <h5> Ecrit par : <%= article.user.first_name %> </h5>
          </div>
          <p> <%= article.description %> </p>
        </div>
        <div class="container-btn">
          <h5><%= article.date %></h5>
          <%= link_to "Je découvre",blog_article_path(article), class:"button btn-yellow-black" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/blog_articles/index.html.erb
<%#= image_tag('https://images.unsplash.com/photo-1470468969717-61d5d54fd036?ixid=MXwxMjA3fDB8MHxzZWFyY2h8ODF8fHNwb3J0cyUyMGdpcmx8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', class: "background-home-image") %>

<div class="content-container">
 <div class="banner-small banner-container">
    <h1>L'After Work</h1>
    <h4 class="mb-4">Découvrez tous nos articles </h4>
  </div>
  <h2 class="blog-index-title">Filtrer par thématiques</h2>

  <% @articles.each do |article| %>
    <div class="blog-card-container">
      <% if article.photos.first %>
        <%= cl_image_tag article.photos.first.key, width: 300, crop: :fill, class:"blog-card-img" %>
      <% end %>
      <div class="blog-card-text-content">
        <div class="blog-card-content">
          <div class="card-title-content">
            <h2><%= link_to article.title, blog_article_path(article) %></h2>
            <h5> Ecrit par : <%= article.user.first_name %> </h5>
              <div class="tag-list-card">
                <% article.tag_list.each do |tag| %>
                  <div class="tag_btn mr-2"><%= tag %></div>
                <% end %>
              </div>
          </div>
          <p> <%= article.description %> </p>
        </div>
        <div class="container-btn">
          <h5><%= article.date.strftime("%d/%m/%Y")  %></h5>
          <%= link_to "Je découvre",blog_article_path(article), class:"button btn-yellow-black" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/blog_articles/new.erb
<div class="content-container">
  <h1>Hello <%#= @user.first_name %> ! Trop cool, Hâte de lire ce nouvel article !</h1>

  <%= simple_form_for(@article) do |f| %>
    <%#= f.input :title %>
    <%#= f.input :description %>
    <%#= f.input :content %>
    <%#= f.button :submit %>
    <div class="form-inputs">
      <%= f.input :title %>
    </div>
    <div class="form-inputs">
      <%= f.input :description %>
    </div>

    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <!-- insert these three line of code below -->
    <div class="form-inputs">
      <%= f.rich_text_area :rich_content %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

</div>

app/views/blog_articles/new.html.erb
<div class="content-container">
  <h1>Hello <%= @user.first_name %> ! Trop cool, Hâte de lire ce nouvel article !</h1>
  <h4>Créer un nouvel article</h4>

  <%= render "form", article: @article %>

</div>

app/views/blog_articles/show.html.erb
<div class="blog-container">
  <div class="mb-5">
    <h1 class = "blog-title"> <%= @article.title %> </h1>
    <div class="tag-list-show">
      <% @article.tag_list.each do |tag| %>
        <div class="tag_btn"><%= tag %></div>
      <% end %>
    </div>
    <div class="author-box">
      <%= cl_image_tag @article.user.avatar.key, width: 60, crop: :fill, class:"avatar" %>
      <div class="author-infos">
        <p> écrit par : <%= @article.user.first_name %> </p>
        <p class="article-date"><%= @article.date.strftime("%d %B, %Y") %></p>
      </div>
    </div>
    <% if @article.photos.first %>
      <%= cl_image_tag @article.photos.first.key, width: 300, crop: :fill, class:"blog-article-banner my-5" %>
    <% end %>
    <p> <%= @article.description %> </p>
    <%= @article.rich_content %>
  </div>


    <%= link_to "back", blog_articles_path, class:"button btn-yellow-black" %>
    <% if @user %>
    <%= link_to "edit", edit_blog_article_path(@article), class:"button btn-yellow-black" %>
    <%= link_to "delete", blog_article_path(@article), class:"button btn-yellow-black",
                                          method: :delete,
                                          data: { confirm: "Are you sure?" } %>

    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AfterProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="content-container">
  <h1>hello there</h1>
</div>

app/views/pages/home.html.erb
<!-- <div class="container">
  <div class="main-banner" style="background-image: url('/assets/background/girl.jpg');">
  </div>
</div> -->

<!-- <div class="background-home"> -->
  <%= image_tag('https://images.unsplash.com/photo-1470468969717-61d5d54fd036?ixid=MXwxMjA3fDB8MHxzZWFyY2h8ODF8fHNwb3J0cyUyMGdpcmx8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', class: "background-home-image") %>
  <%#= image_tag('https://images.unsplash.com/photo-1470468969717-61d5d54fd036?ixid=MXwxMjA3fDB8MHxzZWFyY2h8ODF8fHNwb3J0cyUyMGdpcmx8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', class: "background-home") %>

  <div class="content-container">
    <div class="banner-big banner-container">
      <h1>L'After</h1>
      <h4 class="mb-5 subtitle-light">Work - Sport : découvrez le monde de l'après ! </h4>
      <%= link_to "Je découvre",root_path, class:"button btn-yellow-grey" %>
    </div>
    <div class="mt-5 mb-5 text-padding text-start">
      <h3 class="">Bienvenue dans notre univers</h3>
      <p class="">
        Postremo ad id indignitatis est ventum, ut cum peregrini ob formidatam haut ita dudum alimentorum
        inopiam pellerentur ab urbe praecipites, sectatoribus disciplinarum liberalium inpendio paucis
        sine respiratione ulla extrusis, tenerentur minimarum adseclae veri, quique.
      </p>
    </div>
    <div class="card-container mt-5">
      <div class="home-card">
        <%= image_tag('https://images.unsplash.com/photo-1493612276216-ee3925520721?ixid=MXwxMjA3fDB8MHxzZWFyY2h8OXx8YmxvZ3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', class: "backgound-home-card-image") %>
          <div class="text-content">
            <div class="header-content">
              <a href="#" class="underline-big">Podcast</a>
            </div>
            <h4>sous-titre</h4>
            <%= link_to "Je découvre", blog_articles_path, class:"button btn-yellow-black btn-card"  %>
          </div>
      </div>

      <div class="home-card">
        <%= image_tag('https://images.unsplash.com/photo-1518605360659-2aa9659ef66d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTI5fHwzJTIwd29tZW58ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', class: "backgound-home-card-image") %>
          <div class="text-content">
            <div class="header-content">
              <a href="#" class="underline-big">Qui sommes-nous ?</a>
            </div>
            <h4>sous-titre</h4>
            <%= link_to "Je découvre", about_us_path, class:"button btn-yellow-black btn-card"  %>
          </div>
      </div>

      <div class="home-card">
        <%= image_tag('https://images.unsplash.com/photo-1593164842249-d74fc06dae05?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NXx8eW9nYXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', class: "backgound-home-card-image") %>
          <div class="text-content">
            <div class="header-content">
              <a href="#" class="underline-big">Blog</a>
            </div>
            <h4>sous-titre</h4>
            <%= link_to "Je découvre", blog_articles_path, class:"button btn-yellow-black btn-card"  %>
          </div>
      </div>

      <div class="home-card">
        <%= image_tag('https://images.unsplash.com/photo-1513542992587-cd39ba97057c?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzV8fGJsb2d8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', class: "backgound-home-card-image") %>
          <div class="text-content">
            <div class="header-content">
              <a href="#" class="underline-big">Contactez-nous</a>
            </div>
            <h4>sous-titre</h4>
            <%= link_to "Je découvre", root_path, class:"button btn-yellow-black btn-card"  %>
          </div>
      </div>
    </div>

    <h3 class="text-centered-margin">Retrouvez-nous sur les réseaux sociaux : </h3>
    <div class="social-media-logos">
      <i class="link fab fa-instagram"></i>
      <i class="link fab fa-facebook-square"></i>
      <i class="link fab fa-linkedin"></i>
      <i class="link fas fa-link"></i>
    </div>
  </div>
<!-- </div> -->

app/views/podcasts/_form.html.erb
  <%= simple_form_for(@podcast) do |f| %>
    <%#= f.input :title %>
    <%#= f.input :description %>
    <%#= f.input :content %>
    <%#= f.button :submit %>
    <div class="form-inputs">
      <%= f.input :title %>
    </div>
    <div class="form-inputs">
      <%= f.input :podcast_number %>
    </div>
    <div class="form-inputs">
      <%= f.input :link %>
    </div>
    <div class="form-inputs">
      <%= f.input :description %>
    </div>

    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <!-- insert these three line of code below -->
    <div class="form-inputs">
      <%= f.rich_text_area :rich_content %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class:'button' %>
    </div>
  <% end %>

app/views/podcasts/index.html.erb
<div class="content-container">
 <div class="banner-small banner-container">
    <h1>After Sport</h1>
    <h4 class="mb-4">Découvrez tous nos podcasts </h4>
  </div>
  <h2 class="blog-index-title">Filtrer par thématiques</h2>


  <% @podcasts.each do |podcast| %>
    <div class="blog-card-container">
      <% podcast.guests.each do |guest| %>
        <% if guest.photo %>
          <%= cl_image_tag guest.photo.key, width: 300, crop: :fill, class:"blog-card-img" %>
        <% end %>
      <div class="blog-card-text-content">

        <div class="blog-card-content">
        <iframe allow="autoplay *; encrypted-media *; fullscreen *; clipboard-write" frameborder="0" height="175" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.podcasts.apple.com/fr/podcast/#{podcast.link}"></iframe>
          <div class="card-title-content">
            <h2> #<%= podcast.podcast_number %></h2>
            <h3> <%= podcast.title %> </h3>
            <h5> Invité : <%= guest.first_name %> <%= guest.last_name %> </h5>
          </div>
          <div class="tag-list-card">
            <%# article.tag_list.each do |tag| %>
              <div class="tag_btn mr-2"><%#= tag %></div>
            <%# end %>
          </div>
          <p> <%= podcast.small_description %> </p>
        </div>
        <div class="container-btn">
          <h5><%= podcast.date.strftime("%d/%m/%Y")  %></h5>
          <%= link_to "Je découvre",podcasts_path, class:"button btn-yellow-black" %>
        </div>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/podcasts/new.html.erb
<div class="content-container">
  <h1>Hello <%= @user.first_name %> ! Trop cool, Hâte de lire ce nouvel article !</h1>
  <h4>Rajouter un épisode de podcast</h4>

  <%= render "form", podcast: @podcast %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by l'After team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon content-container">
  <%= link_to "#", class: "navbar-brand" do %>
    <h2>L'After</h1>
    <%#= image_tag "https://p.kindpng.com/picc/s/395-3951579_logo-before-after-text-hd-png-download.png", height: 50, width: 200, crop: :fill %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <!-- <div class="navbar-items"> -->
      <ul class="navbar-nav mr-auto navbar-content">
        <%# if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Blog", blog_articles_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Podcast", podcasts_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown ml-5">
          <%= link_to "", id: "navbarDropdown", data: { toggle: "dropdown" } do %>
            <i class="fas fa-bars"></i>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Contact us", "#", class: "dropdown-item" %>
            <%if user_signed_in? %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
    <!-- </div> -->
      <%# else %>
        <!-- <li class="nav-item">
          <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li> -->
      <%# end %>
    </ul>
  </div>
</div>